core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

minirhizotron_webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('', include('core.urls')),
    path('', include('processing.urls')),

    path('api/', include('rest_framework.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(), name='schema-swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(), name='schema-redoc'),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

core/views.py
from django.views import View
from django.http import HttpResponse
from django.shortcuts import render


class Home(View):
    def get(self, request) -> HttpResponse:
        return render(request, 'core/index.html')

core/templates/core/layout/footer.html
{% load static %}
{% load sass_tags %}
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <span class="mb-3 mb-md-0 text-body-secondary">© Danforth Plant Science Center - Shakoor Lab</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>
</div>

core/templates/core/layout/header.html
{% load static %} {% load sass_tags %}
<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div
            class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"
        >
            <a
                href="/"
                class="navbar-brand d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none"
            >
                <img src="{% static 'safari-pinned-tab.svg' %}" width="32px" height="32px" />
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li>
                    <a href='{% url "core:home" %}' class="nav-link px-3 link-body-emphasis">Rhizotron</a>
                </li>
                <li><a href='{% url "core:home" %}' class="nav-link px-2 link-body-emphasis">Home</a></li>
                <li><a href='{% url "segmentation:dataset_list" %}' class="nav-link px-2 link-body-emphasis">Datasets</a></li>
                <li><a href="#" class="nav-link px-2 link-body-emphasis">Label</a></li>
                <li><a href="#" class="nav-link px-2 link-body-emphasis">Analyze</a></li>
            </ul>

            {% if user.is_authenticated %}
            <div class="dropdown text-end">
                <a
                    href="#"
                    class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                >
                    <img
                        src="{% static 'person-circle.svg' %}"
                        alt="mdo"
                        width="32px"
                        height="32px"
                        class="rounded-circle"
                    />
                </a>
                <ul class="dropdown-menu text-small">
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>
            </div>
            {% else %}
            <div class="text-end">
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="#" class="nav-link px-2 link-body-emphasis">Login</a></li>
                    <li><a href="#" class="nav-link px-2 link-body-emphasis">Sign Up</a></li>
                </ul>
            </div>
            {% endif %}
        </div>
    </div>
</header>